# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://rajgupt.github.io/feat_overlap/"

git_url = "https://github.com/rajgupt/feat_overlap/tree/master/"

def custom_doc_links(name): return None
